### ISSUE TITLE
‘User Story Split’ option is not working (showing) during sprint planning day at some point of time

### ISSUE THREAD

**Issue by Nagarjunareddycarrier** [microsoft/azure-boards-split#28]
We observed that during Sprint planning days at some point of time, ‘User Story Split’ option is not working.
Please find the attached screen shot which was taken on 30th June where the Split option is not seen.

We are facing same issue from long back at sprint planning day the issue happens and at during specific time.

Split
user-story-split-option-not-working-on-sprint-panning-day.PNG
Extension details: -
Extension details
Split a work item to track work that will continue into the next sprint.
Publisher
Microsoft DevLabs
Installed version
0.1.11 (Latest)
Last updated
Apr 13, 2023 at 9:56 AM GMT+5:

<img width="596" alt="user-story-split-option-not-working-on-sprint-panning-day" src="https://github.com/microsoft/azure-boards-split/assets/124865037/2ecc0f03-6c2f-4bac-bc95-7618580e58ac">

**Comment by AminTi** [comment]
Thanks for reporting, can you describe your environment? Can you check if you get any errors in the browser console or network log?

**Comment by AminTi** [comment]
If the issue persists, please inform me.
