### ISSUE TITLE
Split function bug

### ISSUE THREAD

**Issue by dynbn** [microsoft/azure-boards-split#29]
Hello, we would like to raise a bug encountered by one of our users related to the Split functionality. The issue happened while Azure Devops is crashing and then random stories/tasks were moved to a particular sprint. These were either old items or ones from the backlog. Multiple changes were also made automatically which are not initiated by the user, however, the history for the work items indicate that the action was done by the same user. Do you have an idea what may have caused this issue? 

Thank you.

**Comment by AminTi** [comment]
If you can reproduce the bug, we can schedule a web session .

**Comment by AminTi** [comment]
If the issue persists, please inform me.
