### ISSUE TITLE
Split not working on PBIs

### ISSUE THREAD

**Issue by martamela** [microsoft/azure-boards-split#31]
After clicking on the split on the PBI, the split PBI window does not open and the below tasks are not moved to the next sprint.
I have to create a copy of the PBI and manually move the tasks.

**Comment by AminTi** [comment]
Hi, I just tested it, and it worked as expected.
![Screenshot 2024-05-02 at 13 24 32](https://github.com/microsoft/azure-boards-split/assets/54841342/bd9d142a-95d4-4c9c-ac3e-7b5707d4e53c)

**Comment by martamela** [comment]
I just tried and it didn't work. 
Is there a way to "activate/deactivate" the function on a single devops project?
